
"""
### Explanation of Data Fields

- **pacToGrid**: Power sent to the grid (in watts).

- **ppv**: Power generated by photovoltaic (solar) panels (in watts).

- **sysOut**: System output power (in watts).

- **userLoad**: Power consumed by the user (in watts).

- **pacToUser**: Power sent directly to the user (in watts).

- ****: Total energy discharged from the battery to the AC load (in kWh).

### Grafico de AREA (STORAGE ENERGY DAY CHART)
```
|      timestamp      | pacToGrid  |     ppv    |    sysOut  |  userLoad  |  pacToUser |
|---------------------|------------|------------|------------|------------|------------|
| 2024-10-05 00:00:00 |    45.0    |      0     |      0     |    1275    |    1360    | 
| 2024-10-05 00:05:00 |    47.5    |      0     |      0     |    1275    |    1360    |
| 2024-10-05 00:10:00 |    50.0    |      0     |      0     |    1275    |    1360    |
| ...                 |    ...     |    ...     |    ...     |    ...     |    ...     |
| 2024-10-05 23:55:00 |    42.0    |      0     |      0     |    1280    |    1380    |

```

"""
def create_energy_area_chart_table(connection):
    with connection as conn:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS energy_area_chart (
                timestamp TEXT PRIMARY KEY,
                pacToGrid INTEGER,
                ppv INTEGER,
                sysOut INTEGER,
                userLoad INTEGER,
                pacToUser INTEGER
            )
        ''')
        conn.commit()

def insert_energy_area_chart(connection,timestamp,pacToGrid,ppv,sysOut,userLoad,pacToUser):
    with connection as conn:
        cursor = conn.cursor()
        try:
            cursor.execute('''
                INSERT INTO energy_area_chart (timestamp,pacToGrid,ppv,sysOut,userLoad,pacToUser) 
                VALUES ( ?, ?, ?, ?, ?, ?)
            ''', (timestamp,pacToGrid,ppv,sysOut,userLoad,pacToUser))
            conn.commit()
        except Exception as e:
            # Log the error or handle it in a specific way
            print(f"Error inserting Energy Area Chart data: {e}")