
"""
# Explanation
**chargeToday**: The amount of energy charged today (in kWh or another unit).

**chargeTotal**: The total amount of energy charged over time.

**deviceType**: The type of device (e.g., 3 might correspond to a specific type of energy device).

**eDischargeToday**: The amount of energy discharged today.

**eDischargeTotal**: The total amount of energy discharged over time.

**eToGridToday**: The amount of energy sent to the grid today.

**eToGridTotal**: The total amount of energy sent to the grid over time.

**eToUserToday**: The amount of energy used by the user today.

**eToUserTotal**: The total amount of energy used by the user over time.

**epvToday**: The amount of energy generated by photovoltaic (solar panels) today.

**epvTotal**: The total amount of energy generated by photovoltaic over time.

**useEnergyToday**: The amount of energy consumed today.

**useEnergyTotal**: The total amount of energy consumed over time.
"""
def create_storage_total_table(connection):
    with connection as conn:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS storage_total (
                timestamp TEXT PRIMARY KEY,
                chargeToday REAL,
                chargeTotal REAL,
                deviceType REAL,
                eDischargeToday REAL,
                eDischargeTotal REAL,
                eToGridToday REAL,
                eToGridTotal REAL,
                eToUserToday REAL,
                eToUserTotal REAL,
                epvToday REAL,
                epvTotal REAL,
                useEnergyToday REAL,
                useEnergyTotal REAL  
            )
        ''')
        conn.commit()

def insert_storage_total(connection,timestamp, chargeToday,chargeTotal,deviceType,eDischargeToday,eDischargeTotal,eToGridToday,eToGridTotal,eToUserToday,eToUserTotal,epvToday,epvTotal,useEnergyToday,useEnergyTotal):
    with connection as conn:
        cursor = conn.cursor()
        try:
            cursor.execute('''
                INSERT INTO storage_total (timestamp, chargeToday,chargeTotal,deviceType,eDischargeToday,eDischargeTotal,eToGridToday,eToGridTotal,eToUserToday,eToUserTotal,epvToday,epvTotal,useEnergyToday,useEnergyTotal) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (timestamp, chargeToday,chargeTotal,deviceType,eDischargeToday,eDischargeTotal,eToGridToday,eToGridTotal,eToUserToday,eToUserTotal,epvToday,epvTotal,useEnergyToday,useEnergyTotal))
            conn.commit()
        except Exception as e:
            # Log the error or handle it in a specific way
            print(f"Error inserting Storage Total data: {e}")