
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Oct 17 13:02:22 ART 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int ELSE = 20;
  public static final int SEMICOLON = 18;
  public static final int PLUS = 11;
  public static final int RBRACE = 17;
  public static final int RPAREN = 15;
  public static final int INT = 2;
  public static final int EQUAL = 13;
  public static final int WHILE = 21;
  public static final int STAR = 12;
  public static final int RETURN = 6;
  public static final int GREATER = 23;
  public static final int TRUE = 7;
  public static final int IF = 19;
  public static final int LPAREN = 14;
  public static final int LBRACE = 16;
  public static final int ID = 9;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int MAIN = 5;
  public static final int FALSE = 8;
  public static final int error = 1;
  public static final int BOOL = 3;
  public static final int VOID = 4;
  public static final int LESS = 22;
}

